-- DROP TABLE EVENT;
-- DROP TABLE USERS;

Create TABLE EVENT (
	EVENTID		INT	PRIMARY	KEY	NOT	NULL,
	NAME		TEXT	NOT NULL,
	PLACE		TEXT,
	CATEGORY	TEXT,
	DESCRIPTION	TEXT,
	CREATORID	INT	NOT	NULL,
	IMAGE		TEXT,
	DATE		REAL,
	TIME		TEXT
);
CREATE TABLE USERS(
	USERID		INT	PRIMARY	KEY	NOT	NULL,
	EMAIL		TEXT NOT NULL,
	PASSWORD	TEXT NOT NULL

);
CREATE TABLE ATTENDS(
	EVENTID	INT	REFERENCES EVENT(EVENTID),
	USERID	INT	REFERENCES USERS(USERID)

)